### ISSUE TITLE
Error: Malformed property: (Invalid Type) is not a valid type.

### ISSUE THREAD

**Issue by NoahVlncrt** [BenZed/feathers-schema#6]
I am doing my best in setting up a new project for the first time with this package and nedb. I am following the documentation to a tee and when I start the application I get this error.
```
Error: Malformed property: (Invalid Type) is not a valid type.
    at new Property (/home/noah/Projects/CloudComics/api/node_modules/feathers-schema/lib/schema.js:427:49)
    at Schema.addProperty (/home/noah/Projects/CloudComics/api/node_modules/feathers-schema/lib/schema.js:169:45)
    at Schema.addProperty (/home/noah/Projects/CloudComics/api/node_modules/feathers-schema/lib/schema.js:917:126)
    at new Schema (/home/noah/Projects/CloudComics/api/node_modules/feathers-schema/lib/schema.js:903:14)
    at Object.<anonymous> (/home/noah/Projects/CloudComics/api/src/services/issues/issues.hooks.js:2:22)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
I cannot for the life of me figure out what is going on. My schema looks like this.
```
const issuesSchema = new Schema.Schema({
  name: { type: String, required: true },
  cover: { type: String, required: false}, //path to cover img
  tags: { type: [String], default: [], required: true},
  path: { type: String, required: true }, //path on filesystem
  createdAt: { type: Date, default: Date().now }
})
```
From what I can tell from the docs everything is setup correctly it's just not running and it's driving me a little crazy on the inside. Any help would be appreciated.

**Comment by BenZed** [comment]
I'm surprised I haven't come across this, myself.

It's your `tags` array property.

It's expecting it to look like this:
`tags: [{ type: String, default: [], required: true }]`
as opposed to this
`tags: { type: [String], default: [], required: true }`

That said, I feel like both syntaxes are valid, and it's unintuitive to not support the latter. 
I've updated the definition parser to allow the syntax you have here.

There is one more problem with your Schema, the `createdAt` property should look like this:
`createdAt: { type: Date, default: () => new Date() }`

The reasons are two-fold: `Date.now()` returns a number, and if you don't wrap `new Date()` in a function, the default value for `createdAt` will be from when the Schema was created, rather than when the document is created.

Hope this clears everything up!
